Region: eu-west-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t2.medium
  Networking:
    SubnetId: subnet-0801d23d81c163aba # DevWorkspaceVPC/DUB2/Public
  Ssh:
    KeyName: mgiacomo
    AllowedIps: pl-01a74268
  Iam:
    AdditionalIamPolicies:
    - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  Imds:
    Secured: false
Scheduling:
  Scheduler: awsbatch
  AwsBatchQueues:
  - Name: q1
    ComputeResources:
    - Name: cr1
      InstanceTypes: 
        - c5.large # 2 vcPUs
      MinvCpus: 6
      DesiredvCpus: 6
      MaxvCpus: 10
    Networking:
      SubnetIds:
      - subnet-0119509eab22f8ed3 # DevWorkspaceVPC/DUB2/Private
Tags:
  - Key: owner
    Value: giacomo-marciani
#DevSettings:
#  AmiSearchFilters:
#    Owner: "447714826191"