Region: eu-west-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t2.medium
  Networking:
    SubnetId: subnet-0f311877f669b5d23 # DevWorkspaceVPC/DUB2/Public
  Ssh:
    KeyName: mgiacomo
    AllowedIps: pl-01a74268
  Iam:
    AdditionalIamPolicies:
    - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  Imds:
    Secured: false
Scheduling:
  Scheduler: awsbatch
  AwsBatchQueues:
  - Name: queue0
    ComputeResources:
    - Name: queue0-i0
      InstanceTypes: 
      - c5.large
      MinvCpus: 1
      DesiredvCpus: 1
      MaxvCpus: 10
    Networking:
      SubnetIds:
      - subnet-058aeeb0d6bc887cb # DevWorkspaceVPC/DUB2/Private