Region: eu-west-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: subnet-0801d23d81c163aba # DevWorkspaceVPC/DUB2/Public
  Ssh:
    KeyName: mgiacomo
    AllowedIps: pl-01a74268
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    S3Access:
      - BucketName: mgiacomo-workspace
        EnableWriteAccess: false
        KeyName: "*"
  CustomActions:
    OnNodeStart:
      Script: s3://mgiacomo-workspace/MGIACOMO-AWSParallelCluster/cluster-config/custom-actions/Head-OnNodeStart.sh
    OnNodeConfigured:
      Script: s3://mgiacomo-workspace/MGIACOMO-AWSParallelCluster/cluster-config/custom-actions/Head-OnNodeConfigured.sh
    OnNodeUpdated:
#      Script: s3://mgiacomo-workspace/MGIACOMO-AWSParallelCluster/cluster-config/custom-actions/Head-OnNodeUpdated.sh
      Sequence:
        - Script: s3://mgiacomo-workspace/MGIACOMO-AWSParallelCluster/cluster-config/custom-actions/Head-OnNodeUpdated.sh
        - Script: s3://mgiacomo-workspace/MGIACOMO-AWSParallelCluster/cluster-config/custom-actions/Head-OnNodeUpdated.sh
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    QueueUpdateStrategy: DRAIN
  SlurmQueues:
    - Name: q1
      ComputeResources:
        - Name: cr1
          InstanceType: t3.small
          MinCount: 1
          MaxCount: 5
      Networking:
        SubnetIds:
          - subnet-0119509eab22f8ed3 # DevWorkspaceVPC/DUB2/Private
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        S3Access:
          - BucketName: mgiacomo-workspace
            EnableWriteAccess: false
            KeyName: "*"
      CustomActions:
        OnNodeStart:
#          Script: s3://mgiacomo-workspace/MGIACOMO-AWSParallelCluster/cluster-config/custom-actions/Compute-OnNodeStart.sh
          Sequence:
            - Script: s3://mgiacomo-workspace/MGIACOMO-AWSParallelCluster/cluster-config/custom-actions/Compute-OnNodeStart.sh
            - Script: s3://mgiacomo-workspace/MGIACOMO-AWSParallelCluster/cluster-config/custom-actions/Compute-OnNodeStart.sh
        OnNodeConfigured:
#          Script: s3://mgiacomo-workspace/MGIACOMO-AWSParallelCluster/cluster-config/custom-actions/Compute-OnNodeConfigured.sh
          Sequence:
            - Script: s3://mgiacomo-workspace/MGIACOMO-AWSParallelCluster/cluster-config/custom-actions/Compute-OnNodeConfigured.sh
            - Script: s3://mgiacomo-workspace/MGIACOMO-AWSParallelCluster/cluster-config/custom-actions/Compute-OnNodeConfigured.sh
Tags:
  - Key: owner
    Value: giacomo-marciani
#DevSettings:
#  AmiSearchFilters:
#    Owner: "447714826191"