Region: eu-west-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: g4dn.4xlarge  # g4dn.4xlarge, p3.2xlarge, c6g.xlarge
  Networking:
    SubnetId: subnet-0f311877f669b5d23 # DevWorkspaceVPC/DUB2/Public
  Ssh:
    KeyName: mgiacomo
    AllowedIps: pl-01a74268
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # Required to report patching status
  Dcv:
    Enabled: True
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: q1
      ComputeResources:
        - Name: t2small
          InstanceType: t2.small
          MinCount: 0
          MaxCount: 10
      Networking:
        SubnetIds:
          - subnet-058aeeb0d6bc887cb # DevWorkspaceVPC/DUB2/Private
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # Required to report patching status
