Region: eu-west-1
#Region: us-east-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: subnet-0801d23d81c163aba # DevWorkspaceVPC/DUB2/Public
#    SubnetId: subnet-09f90377c5d6dc03d # DevWorkspaceVPC/IAD1/Public
  Ssh:
    KeyName: mgiacomo
    AllowedIps: pl-01a74268
#    AllowedIps: pl-60b85b09
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
  SharedStorageType: Efs
  CustomActions:
    OnNodeStart:
      Script: s3://mgiacomo-workspace/pcluster-configurations/simple/Head-OnNodeStart.sh
    OnNodeConfigured:
      Script: s3://mgiacomo-workspace/pcluster-configurations/simple/Head-OnNodeConfigured.sh
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    QueueUpdateStrategy: DRAIN
  SlurmQueues:
    - Name: q1
      ComputeResources:
        - Name: cr1
          InstanceType: t3.small
          MinCount: 500
          MaxCount: 500
      Networking:
        SubnetIds:
          - subnet-0119509eab22f8ed3 # DevWorkspaceVPC/DUB2/Private
#          - subnet-0ecafb5ea72369193 # DevWorkspaceVPC/IAD1/Private
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
#SharedStorage:
#  # Managed FSxLustre
#  - MountDir: /opt/shared/fsxlustre/managed/1
#    Name: shared-fsxlustre-managed-1
#    StorageType: FsxLustre
#    FsxLustreSettings:
#      StorageCapacity: 1200
#      DeletionPolicy: Delete
#DevSettings:
#  AmiSearchFilters:
#    Owner: "447714826191"