Region: cn-north-1
Image:
  Os: alinux2
  CustomAmi: ami-0906d10d0f5cb774c
HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: subnet-0eccf7f7d197c6dc9 # DevWorkspaceVPC/BJS11/Private
#  Ssh:
#    KeyName: mgiacomo
#    AllowedIps: pl-4eb55027
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws-cn:iam::aws:policy/AmazonSSMManagedInstanceCore
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    QueueUpdateStrategy: DRAIN
  SlurmQueues:
    - Name: q1
      ComputeResources:
        - Name: cr1
          InstanceType: t3.small
          MinCount: 1
          MaxCount: 5
      Networking:
        SubnetIds:
          - subnet-065891c96a0f3ce25 # DevWorkspaceVPC/BJS11/Private
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws-cn:iam::aws:policy/AmazonSSMManagedInstanceCore
#SharedStorage:
#  - MountDir: /opt/shared/fsxlustre/managed/1
#    Name: shared-fsxlustre-managed-1
#    StorageType: FsxLustre
#    FsxLustreSettings:
#      StorageCapacity: 1200
#      DeletionPolicy: Delete
Tags:
  - Key: owner
    Value: giacomo-marciani
#DevSettings:
#  AmiSearchFilters:
#    Owner: "447714826191"