Region: eu-west-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: subnet-0801d23d81c163aba # DevWorkspaceVPC/DUB2/Public
  Ssh:
    KeyName: mgiacomo
    AllowedIps: pl-01a74268
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    QueueUpdateStrategy: DRAIN
  SlurmQueues:
    - Name: q1
      ComputeResources:
        - Name: cr1
          Instances:
            - InstanceType: hpc6a.48xlarge
          MinCount: 32
          MaxCount: 32
          Efa:
            Enabled: true
          DisableSimultaneousMultithreading: true
      Networking:
        SubnetIds:
          - subnet-0119509eab22f8ed3 # DevWorkspaceVPC/DUB2/Private
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
DevSettings:
  InstanceTypesData: '{"hpc6a.48xlarge": {"InstanceType":"hpc6a.48xlarge","SupportedUsageClasses":["on-demand"],"ProcessorInfo":{"SupportedArchitectures":["x86_64"]},"VCpuInfo":{"DefaultVCpus":96,"DefaultCores":96,"DefaultThreadsPerCore":1},"MemoryInfo":{"SizeInMiB":393216},"EbsInfo":{"EncryptionSupport":"supported"},"NetworkInfo":{"MaximumNetworkCards":1,"EfaSupported":true}, "PlacementGroupInfo":{"SupportedStrategies": ["cluster","partition","spread"]}}}'