Region: eu-west-1
Image:
  Os: alinux2
  CustomAmi: ami-00b77abc789121e1e
HeadNode:
  InstanceType: g4dn.4xlarge
  Networking:
    SubnetId: subnet-0f311877f669b5d23 # DevWorkspaceVPC/DUB2/Public
  Ssh:
    KeyName: mgiacomo
    AllowedIps: pl-01a74268 # pl-01a74268 - com.amazonaws.firewall.regional-corp-only (DUB)
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # Required to report patching status
      - Policy: arn:aws:iam::319414405305:policy/DomainCertificateSecretReadPolicy-corp-mgiacomo-com # Required to read AD certificate
    S3Access:
      - BucketName: mgiacomo-workspace
        EnableWriteAccess: false
        KeyName: MGIACOMO-AWSParallelCluster/cluster-config/active-directory/ad.head.post.sh
  CustomActions:
    OnNodeConfigured:
      Script: s3://mgiacomo-workspace/MGIACOMO-AWSParallelCluster/cluster-config/active-directory/ad.head.post.sh
      Args:
        - arn:aws:secretsmanager:eu-west-1:319414405305:secret:DomainCertificateSecret-corp-mgiacomo-com-2YKKMP
        - /opt/parallelcluster/shared/directory_service/domain-certificate.crt
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: q1
      ComputeResources:
        - Name: c5n18xl-efa
          InstanceType: c5n.18xlarge
          MinCount: 1
          MaxCount: 5
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
      Networking:
        SubnetIds:
          - subnet-058aeeb0d6bc887cb # DevWorkspaceVPC/DUB2/Private
        PlacementGroup:
          Enabled: true
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # Required to report patching status
    - Name: q2
      ComputeResources:
        - Name: g4dn4xl
          InstanceType: g4dn.4xlarge
          MinCount: 1
          MaxCount: 5
      Networking:
        SubnetIds:
          - subnet-058aeeb0d6bc887cb # DevWorkspaceVPC/DUB2/Private
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # Required to report patching status
DirectoryService:
  DomainName: corp.mgiacomo.com
  DomainAddr: ldaps://corp.mgiacomo.com
  PasswordSecretArn: arn:aws:secretsmanager:eu-west-1:319414405305:secret:PasswordSecret-corp-mgiacomo-com-kZrYpP
  DomainReadOnlyUser: cn=ReadOnlyUser,ou=Users,ou=CORP,dc=corp,dc=mgiacomo,dc=com
  LdapTlsCaCert: /opt/parallelcluster/shared/directory_service/domain-certificate.crt
  LdapTlsReqCert: hard
#  LdapAccessFilter: "!(CN=UserTeamO*)"
#  LdapAccessFilter: (|(memberOf=CN=TeamTwo,OU=Users,OU=CORP,DC=corp,DC=mgiacomo,DC=com)(memberOf=CN=TeamThree,OU=Users,OU=CORP,DC=corp,DC=mgiacomo,DC=com))
#  LdapAccessFilter: memberOf=CN=EngineeringTeam,OU=Users,OU=CORP,DC=corp,DC=mgiacomo,DC=com
  AdditionalSssdConfigs:
    debug_level: "0xFFF0"
    cache_credentials: False

SharedStorage:
  - MountDir: /opt/mgiacomo/shared/ebs/managed/1
    Name: mgiacomo-shared-ebs-managed-1
    StorageType: Ebs
#  - MountDir: /opt/mgiacomo/shared/ebs/external/1
#    Name: mgiacomo-shared-ebs-external-1
#    StorageType: Ebs
#    EbsSettings:
#      VolumeId: vol-08498724704bd5051
  - MountDir: /opt/mgiacomo/shared/efs/managed/1
    Name: mgiacomo-shared-efs-managed-1
    StorageType: Efs
#  - MountDir: /opt/mgiacomo/shared/efs/external/1
#    Name: mgiacomo-shared-efs-external-1
#    StorageType: Efs
#    EfsSettings:
#      FileSystemId: fs-0f6cc35ff62ab5bff
  - MountDir: /opt/mgiacomo/shared/fsx/managed/1
    Name: mgiacomo-shared-fsx-managed-1
    StorageType: FsxLustre
    FsxLustreSettings:
      StorageCapacity: 1200
#  - MountDir: /opt/mgiacomo/shared/fsx/external/1
#    Name: mgiacomo-shared-fsx-external-1
#    StorageType: FsxLustre
#    FsxLustreSettings:
#      FileSystemId: fs-0bc6f5b1f3a877a83