Region: eu-west-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: subnet-0801d23d81c163aba # DevWorkspaceVPC/DUB2/Public
  Ssh:
    KeyName: mgiacomo
    AllowedIps: pl-01a74268
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    QueueUpdateStrategy: DRAIN
  SlurmQueues:
    - Name: q1
      ComputeResources:
        - Name: cr1
          InstanceType: t3.small
          MinCount: 1
          MaxCount: 5
      Networking:
        SubnetIds:
          - subnet-0119509eab22f8ed3 # DevWorkspaceVPC/DUB2/Private
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      HealthChecks:
        Gpu:
          Enabled: true
#SharedStorage:
#  - MountDir: /opt/shared/fsxlustre/managed/1
#    Name: shared-fsxlustre-managed-1
#    StorageType: FsxLustre
#    FsxLustreSettings:
#      StorageCapacity: 1200
#      DeletionPolicy: Delete
Tags:
  - Key: owner
    Value: giacomo-marciani
#DevSettings:
#  AmiSearchFilters:
#    Owner: "447714826191"