Region: eu-west-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: subnet-0801d23d81c163aba # DevWorkspaceVPC/DUB2/Public
  Ssh:
    KeyName: mgiacomo
    AllowedIps: pl-01a74268 # pl-01a74268 - com.amazonaws.firewall.regional-corp-only (DUB)
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # Required to report patching status
  SharedStorageType: Ebs
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    QueueUpdateStrategy: DRAIN # TERMINATE|DRAIN|RECYCLE_ON_IDLE
  SlurmQueues:
    - Name: q1
      ComputeResources:
        - Name: cr1
          Instances:
            - InstanceType: c5.large # m6g.medium
            - InstanceType: m5.large # c6g.medium
            - InstanceType: t3.large # r6g.medium
          MinCount: 1
          MaxCount: 10
      Networking:
        SubnetIds:
          - subnet-0119509eab22f8ed3 # DevWorkspaceVPC/DUB2/Private
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # Required to report patching status
SharedStorage:
  # External FSx ONTAP
  - MountDir: /opt/shared/fsxontap/external/1
    Name: shared-fsxontap-external-1
    StorageType: FsxOntap
    FsxOntapSettings:
      VolumeId: fsvol-02eb7a51d22fd4f47
