Region: eu-west-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: subnet-0f311877f669b5d23 # DevWorkspaceVPC/DUB2/Public
  Ssh:
    KeyName: mgiacomo
    AllowedIps: pl-01a74268
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    QueueUpdateStrategy: DRAIN
  SlurmQueues:
    - Name: q1
      ComputeResources:
        - Name: cr1
          InstanceType: t3.small
          MinCount: 1
          MaxCount: 5
      Networking:
        SubnetIds:
          - subnet-058aeeb0d6bc887cb # DevWorkspaceVPC/DUB2/Private
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
SharedStorage:
#   Managed EBS
  - MountDir: /opt/shared/ebs/managed/1
    Name: shared-ebs-managed-1
    StorageType: Ebs
    EbsSettings:
      DeletionPolicy: Delete
Tags:
  - Key: owner
    Value: giacomo-marciani
DevSettings:
  AmiSearchFilters:
    Owner: "447714826191"
  Cookbook:
    ChefCookbook: s3://mgiacomo-workspace/parallelcluster/3.10.0/cookbooks/storage-perms/aws-parallelcluster-cookbook-3.10.0.tgz