Region: eu-west-1
Image:
  Os: alinux2
Iam:
  PermissionsBoundary: "arn:aws:iam::319414405305:policy/AdminPermissionsBoundary"
  ResourcePrefix: "aaaaaaaaaa"
  Roles:
    LambdaFunctionsRole: arn:aws:iam::319414405305:role/AdminLambda
HeadNode:
  InstanceType: t3.small
  Networking:
    SubnetId: subnet-0801d23d81c163aba # DevWorkspaceVPC/DUB2/Public
  Ssh:
    KeyName: mgiacomo
    AllowedIps: pl-01a74268
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # Required to report patching status
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    QueueUpdateStrategy: DRAIN
  SlurmQueues:
    - Name: q1
      ComputeResources:
        - Name: cr1
          InstanceType: t3.small
          MinCount: 1
          MaxCount: 5
      Networking:
        SubnetIds:
          - subnet-0119509eab22f8ed3 # DevWorkspaceVPC/DUB2/Private
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
Tags:
  - Key: owner
    Value: giacomo-marciani